# =========================================================================
# GraphQL falso positivo con campo "composer"
# Regla CRS: 932235
# =========================================================================

# =========================================================================
# Excluir GraphQL field "composer" del falso positivo RCE
# CRS Rule: 932235
# =========================================================================

SecRuleUpdateTargetById 932235 "!ARGS:json.query"
