SecRule REQUEST_URI "@beginsWith /api/storage" \
"id:10001,\
phase:1,\
pass,\
nolog,\
ctl:ruleRemoveTargetById=932235;ARGS:json.query,\
ctl:ruleRemoveTargetById=942290;ARGS:json.query"

SecRule REQUEST_URI "@beginsWith /api/auth/users/" \
"id:10002,\
phase:1,\
pass,\
nolog,\
ctl:ruleRemoveTargetById=930120;ARGS_NAMES:json.profile_info"
